# Generated by Django 5.1.4 on 2024-12-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userinteractions",
            name="action",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="published_at",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
